### ISSUE TITLE
Add option to manage specific uid, gid and mode for each file

### ISSUE THREAD

**Issue by Mesado** [fesor/gulp-deb#12]
In our project, we use gulp-deb and it is necessary to specify owner and mode for each file in the builded .deb.
Is it possible to add options to do this?

Thank you so much

**Comment by fesor** [comment]
The only possible way to do this via *.deb archives is using `preinst` script which will handle this. You could generate it in your gulpfile but since this is really rare case I don't think that this should be implemented...
